# Site settings
title: Creative Theme
email: jbennett590@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The themes include a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username:  jbennett590

# Build settings
markdown: kramdown

